{% set name = "skia-pathops" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/skia-pathops-{{ version }}.zip
  sha256: 62ddcc350ebd059e75782f3bf7fa82c13e7e14657eff01c0ef4f497b80064f9f
  patches:
    # use ninja from conda instead
    - disable-virtualenv-creation.patch
    # use gn from conda
    - use-gn-from-conda.patch
    # use cc, cxx set by the environment
    - inherit-cc-cxx-from-environment.patch
    # fix for arm build on linux and mac
    - add-correct-target-cpu.patch  # [build_platform != target_platform]

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - ninja
    - gn
  host:
    - pip
    - python
    - setuptools-scm
    - cython >=0.27
  run:
    - python

test:
  imports:
    - pathops
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fonttools/skia-pathops
  summary: Python access to operations on paths using the Skia library
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - src/cpp/skia-builder/skia/LICENSE

extra:
  recipe-maintainers:
    - pavelzw
    - naveen521kk
